version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/usr/app/src"
      
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=collectio
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      
volumes:
  mongodb_data_container:
