version: '3.8'

services:
  backend:
    build: ./be
    ports:
      - "3000:3000"
    volumes:
      - "./be/src:/usr/app/src"
      
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=collectio
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  frontend:
    build: ./fe
    ports:
      - "8080:3000"
    volumes:
      - "./fe/src:/usr/app/src"
      - "./fe/public:/usr/app/public"
volumes:
  mongodb_data_container:
